[package]
name = "token_vesting"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"

[dev-dependencies]
snforge_std = "0.55.0"
assert_macros = "2.14.0"

[[target.starknet-contract]]
sierra = true
casm = true

[cairo]
enable-gas = true

[scripts]
test = "snforge test"
