[package]
name = "cairo_merge_k_sorted_lists_01"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[cairo]
enable-gas = true

[scripts]
test = "snforge test"

[dependencies]
cairo_execute = "2.14.0"
snforge_std = "0.55.0"
